//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace UnityFramework.Utils
{
	public class Logger
	{
		public static void Debug(string msg)
		{
#if UNITY_EDITOR
			UnityEngine.Debug.Log(msg);
#endif
		}
	}
}

