//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

namespace UnityFramework
{
	public class NotificationDemon : MonoBehaviour
	{
		public bool Running
		{
			set;
			get;
		}
		public NotificationDemon ()
		{

		}

		void Start ()
		{
			Running = true;
			StartCoroutine (LoopCoroutine());
		}

		void OnDestroy()
		{
			Running = false;
		}

		public Action<float> OnUpdateHandler 
		{
			set;
			get;
		}

		IEnumerator LoopCoroutine()
		{
			while (Running) 
			{
				if (null != OnUpdateHandler) 
				{
					OnUpdateHandler(Time.deltaTime);
				}
				yield return new WaitForFixedUpdate();
			}
		}
	}
}

